# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Background"
  url = "#about"
  weight = 10

[[main]]
  name = "Aims"
  url = "#skills"
  weight = 20

[[main]]
  name = "Researchers"
  url = "#accomplishments"
  weight = 30

[[main]]
  name = "Consent"
  url = "#posts"
  weight = 50

[[main]]
  name = "Social"
  url = "#talks"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
[[main]]
   name = "Survey"
   url = "https://redcap.gimr.garvan.org.au/surveys/?s=DJWTL9FAEX"
   weight = 80
